const XLSX = require('xlsx');
const path = require('path');

// Sample customer data with new field structure
const sampleData = [
  {
    'PROPOSAL NUMBER': 'PROP001',
    'PROPOSER CODE': 'PC001',
    'PROPOSER NAME': 'Rajesh Kumar',
    'Business Type': 'New Business',
    'SOURCECODE': 'SC001',
    'CREATED DATE': '2025-01-15',
    'Inwarding User Code': 'IUC001',
    'PROPOSAL INTIMATION DATE': '2025-01-16',
    'Intimation Ageing': '5 days',
    'Intimation Sub Ageing': '2 days',
    'Policy Issue date': '2025-01-20',
    'POLICY STATUS': 'Active',
    'SUBSTATUS': 'Approved',
    'Discrepancy Remark': 'None',
    'Latest Sub Status Date': '2025-01-20',
    'Sub Status Ageing': '0 days',
    'Sub Status Sub Ageing': '0 days',
    'Branch Code': 'BR001',
    'Intermediary CODE': 'INT001',
    'Channel': 'Direct',
    'GO GREEN': 'Yes',
    'combi Flag': 'No',
    'APPLICABLE SUMINUSRED': '500000',
    'PRODUCT NAME': 'Health Shield Plus',
    'RECEIPT TAG': 'RT001',
    'Latest Followup Date': '2025-01-18',
    'Latest Team Name': 'Sales Team A',
    'Intermediary Name': 'PolicyBazaar',
    'INTERMEDIARY CLASFICATION': 'Corporate',
    'INWARDING BRANCH NAME': 'Delhi Branch',
    'EMPLOYEE DISCOUNT': '10%',
    'Cover Type': 'Individual',
    'LG CODE': 'LG001',
    'LEAD ID': 'LD001',
    'PARTNER SP CODE': 'PSC001',
    'Sales Manager Code': 'SM001',
    'Sales Manager Name': 'Amit Sharma',
    'Policy Expiry Date': '2026-01-20',
    'Nationality': 'Indian',
    'GST Exemption': 'No',
    'PREMIUM MODE': 'Annual',
    'Net Premium': '15000',
    'Gross Premium': '17700'
  },
  {
    'PROPOSAL NUMBER': 'PROP002',
    'PROPOSER CODE': 'PC002',
    'PROPOSER NAME': 'Priya Sharma',
    'Business Type': 'Renewal',
    'SOURCECODE': 'SC002',
    'CREATED DATE': '2025-01-18',
    'Inwarding User Code': 'IUC002',
    'PROPOSAL INTIMATION DATE': '2025-01-19',
    'Intimation Ageing': '3 days',
    'Intimation Sub Ageing': '1 day',
    'Policy Issue date': '',
    'POLICY STATUS': 'Pending',
    'SUBSTATUS': 'Under Review',
    'Discrepancy Remark': 'Documents pending',
    'Latest Sub Status Date': '2025-01-21',
    'Sub Status Ageing': '1 day',
    'Sub Status Sub Ageing': '1 day',
    'Branch Code': 'BR002',
    'Intermediary CODE': 'INT002',
    'Channel': 'Partner',
    'GO GREEN': 'No',
    'combi Flag': 'Yes',
    'APPLICABLE SUMINUSRED': '1000000',
    'PRODUCT NAME': 'Family Protect',
    'RECEIPT TAG': 'RT002',
    'Latest Followup Date': '2025-01-21',
    'Latest Team Name': 'Sales Team B',
    'Intermediary Name': 'ABC Insurance Brokers',
    'INTERMEDIARY CLASFICATION': 'Broker',
    'INWARDING BRANCH NAME': 'Mumbai Branch',
    'EMPLOYEE DISCOUNT': '15%',
    'Cover Type': 'Family Floater',
    'LG CODE': 'LG002',
    'LEAD ID': 'LD002',
    'PARTNER SP CODE': 'PSC002',
    'Sales Manager Code': 'SM002',
    'Sales Manager Name': 'Neha Gupta',
    'Policy Expiry Date': '2026-01-25',
    'Nationality': 'Indian',
    'GST Exemption': 'No',
    'PREMIUM MODE': 'Quarterly',
    'Net Premium': '25000',
    'Gross Premium': '29500'
  },
  {
    'PROPOSAL NUMBER': 'PROP003',
    'PROPOSER CODE': 'PC003',
    'PROPOSER NAME': 'Vikram Singh',
    'Business Type': 'New Business',
    'SOURCECODE': 'SC003',
    'CREATED DATE': '2025-01-20',
    'Inwarding User Code': 'IUC003',
    'PROPOSAL INTIMATION DATE': '2025-01-21',
    'Intimation Ageing': '1 day',
    'Intimation Sub Ageing': '0 days',
    'Policy Issue date': '2025-01-22',
    'POLICY STATUS': 'Issued',
    'SUBSTATUS': 'Completed',
    'Discrepancy Remark': 'None',
    'Latest Sub Status Date': '2025-01-22',
    'Sub Status Ageing': '0 days',
    'Sub Status Sub Ageing': '0 days',
    'Branch Code': 'BR003',
    'Intermediary CODE': 'INT003',
    'Channel': 'Direct',
    'GO GREEN': 'Yes',
    'combi Flag': 'No',
    'APPLICABLE SUMINUSRED': '750000',
    'PRODUCT NAME': 'Senior Care',
    'RECEIPT TAG': 'RT003',
    'Latest Followup Date': '2025-01-21',
    'Latest Team Name': 'Sales Team C',
    'Intermediary Name': 'PolicyBazaar',
    'INTERMEDIARY CLASFICATION': 'Corporate',
    'INWARDING BRANCH NAME': 'Bangalore Branch',
    'EMPLOYEE DISCOUNT': '5%',
    'Cover Type': 'Individual',
    'LG CODE': 'LG003',
    'LEAD ID': 'LD003',
    'PARTNER SP CODE': 'PSC003',
    'Sales Manager Code': 'SM003',
    'Sales Manager Name': 'Rahul Verma',
    'Policy Expiry Date': '2026-01-22',
    'Nationality': 'Indian',
    'GST Exemption': 'Yes',
    'PREMIUM MODE': 'Annual',
    'Net Premium': '35000',
    'Gross Premium': '41300'
  }
];

// Create workbook
const workbook = XLSX.utils.book_new();

// Convert data to worksheet
const worksheet = XLSX.utils.json_to_sheet(sampleData);

// Add worksheet to workbook
XLSX.utils.book_append_sheet(workbook, worksheet, 'Proposals');

// Write to file
const outputPath = path.join(__dirname, 'sample-customers.xlsx');
XLSX.writeFile(workbook, outputPath);

console.log(`Sample Excel file created: ${outputPath}`);
console.log(`Total records: ${sampleData.length}`);
